'use client';
import { useState } from 'react';
import { ShieldCheck,Check,X,PencilSimple } from '@phosphor-icons/react';
import { motion } from 'framer-motion';
import type { ApprovalRequest } from '@/types/domain';
import { services } from '@/services';
import { useAction } from '@/hooks/use-services';
import { Badge,ErrorState,StatusBadge } from '@/components/common/ui';
import { Button } from '@/components/ui/button';
export function ApprovalCard({approval:a}:{approval:ApprovalRequest}){const action=useAction(),[editing,setEditing]=useState(false),[inputs,setInputs]=useState(a.inputs);return <motion.section initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="approval-card" aria-label="Action approval"><div className="row between"><div className="row"><ShieldCheck size={21} weight="duotone"/><strong>{a.action}</strong></div><StatusBadge status={a.status==='pending'?'Approval required':a.status}/></div><p>{a.consequence}</p><div className="approval-fields">{editing?<><label className="field">Recipient<input type="email" value={inputs.recipient} onChange={e=>setInputs({...inputs,recipient:e.target.value})}/></label><label className="field">Subject<input value={inputs.subject} onChange={e=>setInputs({...inputs,subject:e.target.value})}/></label><label className="field">Message / ticket description<textarea rows={8} value={inputs.body} onChange={e=>setInputs({...inputs,body:e.target.value})}/></label></>:<><div className="row"><span className="muted tiny">TO</span><strong>{a.inputs.recipient}</strong></div><h4>{a.inputs.subject}</h4><p className="draft-preview">{a.inputs.body}</p></>}</div>{a.status==='pending'&&<div className="row wrap"><Button variant="default" disabled={action.isPending} onClick={()=>void action.mutateAsync(()=>services.approvals.resolve(a.id,true,editing?inputs:undefined)).catch(()=>{})}><Check size={16}/>{action.isPending?'Completing…':a.action.includes('ticket')?'Approve & create ticket':'Approve & send'}</Button><Button disabled={action.isPending} onClick={()=>setEditing(!editing)}><PencilSimple size={15}/>{editing?'Cancel edit':'Edit'}</Button><Button variant="ghost" disabled={action.isPending} onClick={()=>void action.mutateAsync(()=>services.approvals.resolve(a.id,false)).catch(()=>{})}><X size={15}/>Reject</Button></div>}{action.error&&<ErrorState message={action.error.message}/>}</motion.section>;}
